### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zilongzixue** [click33/sa-plus#2]
代码生成要是集成mybatis-plus 就好了

**Comment by click33** [comment]
已经适配 mybatis-plus了，可以在生成前配置是否生成mybatis-plus结构的代码

**Comment by zilongzixue** [comment]
> 已经适配 mybatis-plus了，可以在生成前配置是否生成mybatis-plus结构的代码

好的

**Comment by click33** [comment]
问题已解决

**Comment by zilongzixue** [comment]
> 问题已解决
感谢省长
