### ISSUE TITLE
SQL报错修改

### ISSUE THREAD

**Issue by fairychao** [click33/sa-plus#5]
SpAdminMapper.xml
select *,
		(select role_name from sp_role where id = sp_admin.role_id) as role_name 
		from sp_admin 

上面SQL执行异常（MySQL 版本 5.7.28）
### The error may exist in com/pj/project4sp/admin/SpAdminMapper.xml

建议修改 sa-plus.sql
sp_role 表  name 改了  role_name

**Comment by click33** [comment]
已修正
